/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppWatchlistRouteImport } from './routes/app.watchlist'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppScenariosRouteImport } from './routes/app.scenarios'
import { Route as AppNewsRouteImport } from './routes/app.news'
import { Route as AppMapRouteImport } from './routes/app.map'
import { Route as AppDependenciesRouteImport } from './routes/app.dependencies'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWatchlistRoute = AppWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScenariosRoute = AppScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsRoute = AppNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppDependenciesRoute = AppDependenciesRouteImport.update({
  id: '/dependencies',
  path: '/dependencies',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/alerts': typeof AppAlertsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dependencies': typeof AppDependenciesRoute
  '/app/map': typeof AppMapRoute
  '/app/news': typeof AppNewsRoute
  '/app/scenarios': typeof AppScenariosRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/watchlist': typeof AppWatchlistRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dependencies': typeof AppDependenciesRoute
  '/app/map': typeof AppMapRoute
  '/app/news': typeof AppNewsRoute
  '/app/scenarios': typeof AppScenariosRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/watchlist': typeof AppWatchlistRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/alerts': typeof AppAlertsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dependencies': typeof AppDependenciesRoute
  '/app/map': typeof AppMapRoute
  '/app/news': typeof AppNewsRoute
  '/app/scenarios': typeof AppScenariosRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/watchlist': typeof AppWatchlistRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/alerts'
    | '/app/dashboard'
    | '/app/dependencies'
    | '/app/map'
    | '/app/news'
    | '/app/scenarios'
    | '/app/settings'
    | '/app/watchlist'
    | '/auth/login'
    | '/auth/signup'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/alerts'
    | '/app/dashboard'
    | '/app/dependencies'
    | '/app/map'
    | '/app/news'
    | '/app/scenarios'
    | '/app/settings'
    | '/app/watchlist'
    | '/auth/login'
    | '/auth/signup'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/alerts'
    | '/app/dashboard'
    | '/app/dependencies'
    | '/app/map'
    | '/app/news'
    | '/app/scenarios'
    | '/app/settings'
    | '/app/watchlist'
    | '/auth/login'
    | '/auth/signup'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/watchlist': {
      id: '/app/watchlist'
      path: '/watchlist'
      fullPath: '/app/watchlist'
      preLoaderRoute: typeof AppWatchlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scenarios': {
      id: '/app/scenarios'
      path: '/scenarios'
      fullPath: '/app/scenarios'
      preLoaderRoute: typeof AppScenariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/news': {
      id: '/app/news'
      path: '/news'
      fullPath: '/app/news'
      preLoaderRoute: typeof AppNewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/map': {
      id: '/app/map'
      path: '/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dependencies': {
      id: '/app/dependencies'
      path: '/dependencies'
      fullPath: '/app/dependencies'
      preLoaderRoute: typeof AppDependenciesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDependenciesRoute: typeof AppDependenciesRoute
  AppMapRoute: typeof AppMapRoute
  AppNewsRoute: typeof AppNewsRoute
  AppScenariosRoute: typeof AppScenariosRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWatchlistRoute: typeof AppWatchlistRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDependenciesRoute: AppDependenciesRoute,
  AppMapRoute: AppMapRoute,
  AppNewsRoute: AppNewsRoute,
  AppScenariosRoute: AppScenariosRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWatchlistRoute: AppWatchlistRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
